CREATE TABLE [dbo].[Competition]
(
	[Id]		INT		NOT NULL	IDENTITY(1, 1),
	[Created]	DATETIME	NOT NULL,
	[Modified]	DATETIME	NOT NULL,
	[Name]		NVARCHAR(255)	NOT NULL,
	[SportId]	INT		NOT NULL,
	[CountryId]	INT		NULL,
	[LogoURL]	NVARCHAR(4000)	NULL,
	
	CONSTRAINT [PK_COMPETITION_ID]		PRIMARY KEY ([Id]),
	CONSTRAINT [FK_COMPETITION_SPORT_ID]	FOREIGN KEY ([SportId])	  REFERENCES [dbo].[Sport]([Id]),
	CONSTRAINT [FK_COMPETITION_COUNTRY_ID]	FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country]([Id])
)