CREATE TABLE [dbo].[Event]
(
	[Id]		BIGINT		NOT NULL	IDENTITY (1, 1),
	[MatchId]	BIGINT		NOT NULL,
	[TeamId]	INT		NOT NULL,
	[Type]		SMALLINT	NOT NULL,
	[Description]	NVARCHAR(255)	NULL,
	[Time]		DATETIME	NOT NULL,

	CONSTRAINT [PK_EVENT_ID]	PRIMARY KEY ([Id]),
	CONSTRAINT [FK_EVENT_MATCH_ID]	FOREIGN KEY ([MatchId]) REFERENCES [dbo].[Match]([Id]),
	CONSTRAINT [FK_EVENT_TEAM_ID]	FOREIGN KEY ([TeamId])	REFERENCES [dbo].[Team]([Id])
)
