CREATE TABLE [dbo].[Match]
(
	[Id]		BIGINT		NOT NULL	IDENTITY(1, 1),
	[Created]	DATETIME	NOT NULL,
	[Modified]	DATETIME	NOT NULL,
	[HomeTeamId]	INT		NOT NULL,
	[AwayTeamId]	INT		NOT NULL,
	[SeasonId]	INT		NOT NULL,
	[Description]	NVARCHAR(255)	NULL,
	[StartTime]	DATETIME	NOT NULL,

	CONSTRAINT [PK_MATCH_ID]		PRIMARY KEY ([Id]),
	CONSTRAINT [FK_MATCH_HOME_TEAM_ID]	FOREIGN KEY ([HomeTeamId])	REFERENCES [dbo].[Team]([Id]),
	CONSTRAINT [FK_MATCH_AWAY_TEAM_ID]	FOREIGN KEY ([AwayTeamId])	REFERENCES [dbo].[Team]([Id]),
	CONSTRAINT [FK_MATCH_SEASON_ID]		FOREIGN KEY ([SeasonId])	REFERENCES [dbo].[Season]([Id]),
)