CREATE TABLE [dbo].[Player]
(
	[Id]		INT		NOT NULL	IDENTITY (1, 1),
	[Created]	DATETIME	NOT NULL,
	[Modified]	DATETIME	NOT NULL,
	[Born]		DATE		NOT NULL,
	[TeamId]	INT		NOT NULL,
	[Name]		NVARCHAR(255)	NOT NULL,
	[PicURL]	NVARCHAR(4000)	NULL,

	CONSTRAINT [PK_PLAYER_ID]	PRIMARY KEY ([Id]),
	CONSTRAINT [FK_PLAYER_TEAM_ID]	FOREIGN KEY ([TeamId]) REFERENCES [dbo].[Team]([Id])	
)