CREATE TABLE [dbo].[Team]
(
	[Id]		INT		NOT NULL	IDENTITY(1, 1),
	[Created]	DATETIME	NOT NULL,
	[Modified]	DATETIME	NOT NULL,
	[Founded]	DATE		NOT NULL,
	[Name]		NVARCHAR(255)	NOT NULL,
	[Stadium]	NVARCHAR(255)	NOT NULL,
	[LogoURL]	NVARCHAR(4000)	NULL,
	[StadiumPicURL]	NVARCHAR(4000)	NULL,
	[CountryId]	INT		NOT NULL,
	[SportId]	INT		NOT NULL,
	
	CONSTRAINT [PK_TEAM_ID]		PRIMARY KEY ([Id]),
	CONSTRAINT [FK_TEAM_COUNTRY_ID]	FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country]([Id]),
	CONSTRAINT [FK_TEAM_SPORT_ID]	FOREIGN KEY ([SportId])   REFERENCES [dbo].[Sport]([Id])	
)